### ISSUE TITLE
f:viewParam is lost after an f:ajax listener is run

### ISSUE THREAD

**Issue by javaserverfaces** [javaee/mojarra#2621]
The values of f:viewParam components are lost after the processing of an f:ajax listener. For example, if there is an f:ajax listener to an input component for a valueChange event and that event is fired, when a postback is invoked using a commandButton, the view parameter's value is null. If the valueChange event does not fire, the view parameter is retained.

I've included a simple example WAR that demonstrates this. Deploy and visit /example/example.jsf?param=test. Click submit button and the view parameter stays. Click the checkbox (which has an AJAX valueChange listener) then submit and the view parameter is cleared.
#### Environment
GlassFish 3.1.2.2, JBoss AS 7.1.1
#### Affected Versions
[2.1.7, 2.1.14]

**Comment by maulikjn** [comment]
Was this issue ever fixed? Can someone please suggest the solution to this behavior?
