### ISSUE TITLE
Wrong doctype when one is specified in composite view

### ISSUE THREAD

**Issue by javaserverfaces** [javaee/mojarra#2824]
I'm having a problem with DOCTYPE. Everything used to work well on Mojarra 2.1.13 but doesn't work well but when I moved to JBoss 6.1\. Alpha1 (i.e. 7.2.0.Final) which uses Mojarra 2.1.18\. I also tried 2.1.19, but the same result.

In the master template at the beginning I have following doctype
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

In composite view that uses this template I have following doctype:
<!DOCTYPE composite PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

Well, what happens is that the composite doctype is rendered instead of html one.
#### Environment
jboss eap 6.1 Alpha1
#### Affected Versions
[2.1.18, 2.1.19]

**Comment by Quix0r** [comment]
Needs re-opening, people, including myself have still the issue:

https://stackoverflow.com/questions/31556859/how-to-specify-the-target-doctype-in-jsf-2-2?rq=1
https://stackoverflow.com/questions/45537018/doctype-not-rendered-in-jsf-master-template

The last one is asked by me and as you can see I use `h:doctype` and nowhere else any doctype.
