### ISSUE TITLE
DateTimeConverter sets TimeZone only for Dates, not for DateTimes

### ISSUE THREAD

**Issue by User20181107** [javaee/mojarra#4387]
javax.faces.convert.DateTimeConverter.FormatWrapper.setTimeZone(TimeZone) sets TimeZone only for the DateFormat df, not for the DateTimeFormat dtf. Copying the class locally and changing the method to read:
```
private void setTimeZone(TimeZone zone) {
            if (null != df) {
                df.setTimeZone(zone);
            }
            if (null != dtf) {
                dtf = dtf.withZone(zone.toZoneId());
            }
        }
```
... gives us the expected behaviour - we see datetimes output by the converter in the specified timezone.

**Comment by ren-zhijun-oracle** [comment]
please file the issue in https://github.com/eclipse-ee4j/mojarra/issues
