### ISSUE TITLE
Scripts with CDATA cause "empty response" error on Ajax render

### ISSUE THREAD

**Issue by stiemannkj1** [javaee/mojarra#4388]
Steps to reproduce:

1. Create a view with the following `f:form`:

	```
	<h:form>
		<h:commandButton value="rerender CDATA script container">
			<f:ajax render="cdataScriptContainer" />
		</h:commandButton>
		<h:panelGroup id="cdataScriptContainer">
			<h:outputScript>//<![CDATA[
				alert('script loaded');
			//]]></h:outputScript>
		</h:panelGroup>
	</h:form>
	```

2. Navigate to the view.
3. Click the *rerender CDATA script container* button.

If the bug is fixed the *script loaded* alert will appear.

If the bug still exists the browser will display an error message similar to the following:

> emptyResponse: An empty response was received from the server.  Check server error logs.

**Comment by stiemannkj1** [comment]
This issue did not exist for Mojarra `2.2.16`. It is a regression in `2.2.17` caused by the fix for #4358.

**Comment by stiemannkj1** [comment]
Fixed by reverting the incomplete fix for #4358.

**Comment by melloware** [comment]
@stiemannkj1 hasn't this project been migrated to eclipse-ee?  Is this project still active because i am confused where to look for Mojarra issues.

**Comment by stiemannkj1** [comment]
@melloware, as far as I know this project is still receiving updates from Oracle for `2.2.x`, `2.1.x`, and `1.2.x` versions. Mainly Oracle has just been fixing security vulnerabilities. I think `2.3.x` is completely under the Jakarta EE name now though. But I have no inside knowledge about Oracle. This is only what I've gleaned from the commits that this project has received. Anyway, since this bug affects `2.2.x`, I figured I'd fix it in hopes that we'll get another `2.2.x` release.

**Comment by melloware** [comment]
Thanks!   This transition from Oracle to Eclipse I don't think will end up being very smooth.

**Comment by arjantijms** [comment]
> Thanks! This transition from Oracle to Eclipse I don't think will end up being very smooth.

Understatement of the year, but indeed, it hasn't been smooth at all. In the larger scheme of things that has pushed back everything at least 2 years, but we're working hard and everyone from both Oracle and Eclipse are really helpful.
