### ISSUE TITLE
Release 2.2.19

### ISSUE THREAD

**Issue by stiemannkj1** [javaee/mojarra#4397]
I'm requesting a release of `2.2.19` with the fix for "Bug 28978718 - HIGH-LEVEL VULNERABILITY WITHIN ORACLE MOJARRA JSF V2.2": https://github.com/javaserverfaces/mojarra/commit/6b8f467ac96c862364dff97655a8e4cea4ad3ec8. `2.3.9` and `2.2.8-32` appear to already have been released with this fix. There are also other fixes for regressions that would be useful in this release.

@ruolli, @ren-zhijun-oracle, @edburns, @manfredriem, @javaserverfaces

**Comment by ruolli** [comment]
Mojarra javax.faces.:2.2.19 released: 
https://maven.java.net/content/repositories/releases/org/glassfish/javax.faces/2.2.19/
